<?php
if (condition) {
    # code...
    if (condition) {
        # code...
    } else {
        # code...
        if (condition) {
            # code...
        } else {
            # code...
            while ($a <= 10) {
                # code...
                if (condition) {
                    # code...
                } else {
                    # code...
                }
            }
        }
    }
} else {
    # code...
}
